version: "3.7"
services:
  app:
    build: ./
    container_name: php-mysql-to-cloud-spanner
    environment:
      ENVIRONMENT: "development"
      XDEBUG_MODE: "coverage"
    volumes:
      - $PWD:/var/www/html:delegated
    networks:
      - default