name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: json, pdo, grpc
          coverage: xdebug
          tools: php-cs-fixer, phpunit, codeception, composer

      - name: Install Composer
        run: composer install

      - name: Detect coding standard violations
        run: vendor/bin/phpcs -sv --extensions=php --standard=PSR12 --ignore=vendor,tests,c3.php .

      - name: Execute tests
        run: vendor/bin/codecept run --coverage --coverage-text --coverage-xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}